import { NextRequest, NextResponse } from 'next/server';
import { verifyMcpToken, resolveBoundAgentId } from '@/lib/mcp';
import { db } from '@/db';
import { threadMessages } from '@/db/schema';
import { and, eq, sql, asc } from 'drizzle-orm';
import { broadcastMcpEvent } from '@/lib/pubsub';
async function actor(req:NextRequest){const auth=await verifyMcpToken(req);if(auth.error)throw new Error('Unauthorized');const companyId=auth.companyToken!.companyId;const agentId=await resolveBoundAgentId(companyId,auth.companyToken!,new URL(req.url).searchParams.get('agentId'));if(!agentId)throw new Error('Agent required');return {companyId,agentId};}
export async function GET(req:NextRequest){try{const {companyId,agentId}=await actor(req);const commands=await db.select().from(threadMessages).where(and(eq(threadMessages.companyId,companyId),eq(threadMessages.targetAgentId,agentId),eq(threadMessages.senderType,'system'),eq(threadMessages.deliveryState,'queued'),sql`${threadMessages.metadataJson} ? 'runtimeGoalRequest'`)).orderBy(asc(threadMessages.createdAt),asc(threadMessages.id)).limit(20);return NextResponse.json({commands});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Goal polling failed'},{status:403});}}
export async function POST(req:NextRequest){try{const {companyId,agentId}=await actor(req);const body=await req.json();if(typeof body.commandId!=='string'||!body.goal||typeof body.goal.status!=='string'||JSON.stringify(body.goal).length>16000)return NextResponse.json({error:'Invalid goal status'},{status:400});const [message]=await db.update(threadMessages).set({deliveryState:'resolved',text:typeof body.goal.message==='string'?body.goal.message.slice(0,1000):`Objective ${body.goal.status}`,metadataJson:sql`${threadMessages.metadataJson} || ${JSON.stringify({runtimeGoalState:body.goal})}::jsonb`}).where(and(eq(threadMessages.companyId,companyId),eq(threadMessages.targetAgentId,agentId),eq(threadMessages.id,body.commandId),eq(threadMessages.senderType,'system'),sql`${threadMessages.deliveryState} IN ('queued','resolved')`,sql`${threadMessages.metadataJson} ? 'runtimeGoalRequest'`)).returning();if(message)broadcastMcpEvent(companyId,{type:'thread_message',threadId:message.threadId,message});return NextResponse.json({ok:!!message});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Goal status failed'},{status:403});}}
