'use client';
import { useCallback, useEffect, useState } from 'react';
type Goal = {contract?:string;status:string;objective?:string;turnsUsed?:number;maxTurns?:number;message?:string;waiting?:boolean};
export function AgentGoalControls({agentId}:{agentId:string}){
    const [supported,setSupported]=useState(false),[goal,setGoal]=useState<Goal|null>(null),[pending,setPending]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[objective,setObjective]=useState(''),[maxTurns,setMaxTurns]=useState(10);
    const load=useCallback(async()=>{try{const response=await fetch(`/api/agents/${agentId}/goal`);if(!response.ok)return;const result=await response.json();setSupported(result.supported);setGoal(result.goal);setPending(result.pending);}catch{/* The conversation remains usable during a temporary disconnect. */}},[agentId]);
    useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer);},[load]);
    async function act(action:string){setBusy(true);setError(null);try{const response=await fetch(`/api/agents/${agentId}/goal`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,objective,maxTurns})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not update objective');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Could not update objective');}finally{setBusy(false);}}
    if(!supported)return null;
    const active=goal?.status==='active',paused=goal?.status==='paused';
    const button='min-h-11 rounded-lg border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
    return <details className="mx-2 my-2 rounded-xl border border-zinc-800 bg-zinc-950/50 text-zinc-200 sm:mx-4"><summary className="min-h-11 cursor-pointer px-3 py-3 text-sm font-medium">Objective{pending?' · awaiting runtime':active?goal.waiting?' · waiting':' · working':paused?' · paused':goal?.status==='done'?' · completed':''}</summary><div className="max-h-[45dvh] space-y-3 overflow-y-auto border-t border-zinc-800 p-3 sm:max-h-80">
        {pending&&<p role="status" className="text-xs text-zinc-400">Waiting for the runtime to confirm. Older Hermes images need an update to support objectives.</p>}
        {goal&&<div><p className="max-h-28 overflow-y-auto break-words text-sm">{goal.objective}</p><p className="mt-1 text-xs text-zinc-400">{goal.message}</p>{goal.maxTurns? <p className="mt-1 text-xs text-zinc-400">{goal.turnsUsed??0} / {goal.maxTurns} turns</p>:null}</div>}
        {goal?.contract && <details className="rounded-lg border border-zinc-800"><summary className="min-h-11 cursor-pointer px-3 py-3 text-xs text-zinc-400">Completion criteria</summary><p className="max-h-32 overflow-y-auto whitespace-pre-wrap break-words px-3 pb-3 text-xs text-zinc-300">{goal.contract}</p></details>}
        {(active||paused)?<div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={busy||pending} onClick={()=>void act(active?'pause':'resume')}>{active?'Pause':'Resume'}</button><button type="button" className={button} disabled={busy||pending} onClick={()=>void act('clear')}>Clear objective</button></div>:<form onSubmit={event=>{event.preventDefault();void act('start');}} className="space-y-3"><label className="block text-xs text-zinc-400">What should the agent finish?<textarea value={objective} onChange={event=>setObjective(event.target.value)} maxLength={4000} rows={3} required className="mt-1 w-full resize-y rounded-lg border border-zinc-700 bg-zinc-900 p-3 text-base text-zinc-100" placeholder={'Describe the outcome and how to verify it.\nverify: …'} /></label><div className="flex flex-wrap items-center justify-between gap-2"><label className="flex items-center gap-2 text-xs text-zinc-400">Turn limit<select aria-label="Objective turn limit" value={maxTurns} onChange={event=>setMaxTurns(Number(event.target.value))} className="min-h-11 rounded-lg border border-zinc-700 bg-zinc-900 px-2 text-sm text-zinc-100">{[5,10,20].map(n=><option key={n} value={n}>{n}</option>)}</select></label><button type="submit" disabled={busy||pending||!objective.trim()} className={button}>{busy?'Sending…':'Start objective'}</button></div><p className="text-xs leading-relaxed text-zinc-500">Continues until verified, paused, blocked or the turn limit is reached. Agent and company budgets still apply.</p></form>}
        {error&&<p role="alert" className="text-sm text-red-300">{error}</p>}
    </div></details>;
}
